
image:
  file: .gitpod.Dockerfile
  
vscode:
  extensions:
    - connorshea.vscode-ruby-test-adapter@0.6.1:HO9rpcRv7bmRIuo7Mty/zg==
    - hbenl.vscode-test-explorer@2.15.0:koqDUMWDPJzELp/hdS/lWw==
    - rebornix.ruby@0.27.0:QyGBeRyslOfdRgOPRGm6PQ==
    - wingrunr21.vscode-ruby@0.27.0:beIqQUhLRuJ5Vao4B2Lyng==
    - karunamurti.haml@1.1.0:twCwOYt3/Ttfb3+iwblPDA==
    - octref.vetur@0.25.0:UofirBhedyhdx/jCnPeJDg==
    - dbaeumer.vscode-eslint@2.1.3:1NRvj3UKNTNwmYjptmUmIw==
    - GitLab.gitlab-workflow@3.3.0:50q1byIi4M01G9qrTCCAYQ
